import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

export const revalidate = 0;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/">home</Link>
          <Link href="/list">list</Link>
          <Link href="/write">등록</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
